### ISSUE TITLE
Do you mind if I take this project (or at least the idea) to develop it?

### ISSUE THREAD

**Issue by JeysonFlores** [cassidyjames/codestash#1]
The title says it all

**Comment by cassidyjames** [comment]
@JeysonFlores I would be down for you to work on this! Would you be open to working on it together under a new GitHub org? I'd like to be involved on the design and UX side but would love to hand off the development.

**Comment by JeysonFlores** [comment]
Thanks for answering and yes, I'm open to work on a Github org if you want, also it'd be great if you contribute to the UX design.  However what I was planning to do is take this code and translate it to Python (since it's the language I have most proficiency with) and also because due to this app's nature I think I'd have to make use of some really good python libraries to speed the things up a little bit. If you don't mind about that, then count with me!

**Comment by cassidyjames** [comment]
@JeysonFlores hm, I'd personally prefer to stick with Vala as that way I could actually contribute to the code _a bit_ when needed, e.g. prototyping things. But if you wanted to do a similar Python app I would be happy to help out with UX, still! I do think I'd like to reserve the name `CodeStash` for this Vala project in case I do ever get around to working on it more, though.

**Comment by JeysonFlores** [comment]
Ok got it, Thanks for taking your time to answer!
